### ISSUE TITLE
下载文件后端接口设计

### ISSUE THREAD

**Issue by BallsperCat** [simter/simter-file#12]

**Comment by BallsperCat** [comment]
创建分支号：feature/design-download-interface，开始执行任务。

**Comment by BallsperCat** [comment]
【提交说明】本次提交添加了附件 Service、Dao 下载方法接口设计，详见：[687ff7](https://github.com/simter/simter-file/commit/687ff734f9e3d53c93ab95b04c758d92b8db32e2)

**Comment by rj-hwang** [comment]
Checked OK.

**Comment by BallsperCat** [comment]
已将 feature/design-download-interface 分支下载放接口设计合并到 master 分支，详见：[969804](https://github.com/simter/simter-file/commit/9698042bcfafd8b67545142d27f6524377711478)

**Comment by BallsperCat** [comment]
已将 AttachmentService 实现合并到 master 分支，并在 AttachmentDao 的 JPA 实现添加了下载接口的空实现，详见：[9f767a](https://github.com/simter/simter-file/commit/9f767a389ebec38c1855278af6b78328dc756d3a)

**Comment by rj-hwang** [comment]
添加了 [AttachmentDao 的 JPA 实现](https://github.com/simter/simter-file/issues/14)
