### ISSUE TITLE
下载文件 Http 接口设计

### ISSUE THREAD

**Issue by laujeff23** [simter/simter-file#13]

**Comment by laujeff23** [comment]
添加 [Download-One-File](https://github.com/simter/simter-file/wiki/Download-One-File) Http 接口设计

**Comment by rj-hwang** [comment]
两点问题：
1. Content-Type 不需要 charset=utf-8，因为是二进制流。
2. 缺常规下载文件的 header，如 Content-Length、Content-Disposition。
3. Response 中要添加 body 占位符。

**Comment by laujeff23** [comment]
修正相关问题，详见： [Download-One-File](https://github.com/simter/simter-file/wiki/Download-One-File)

**Comment by rj-hwang** [comment]
Check and pass

**Comment by rj-hwang** [comment]
`GET /{id}` should response `404 Not Found` if not exists. Repatched the design.
