### ISSUE TITLE
下载文件 Http 接口实现

### ISSUE THREAD

**Issue by laujeff23** [simter/simter-file#15]

**Comment by laujeff23** [comment]
实现下载文件 Http 接口，已合并到 master 分支，详见 [commit-fcbb930](https://github.com/simter/simter-file/commit/fcbb93084122d49dcf1a570b280aaefbe283e248)

**Comment by laujeff23** [comment]
【未解决的问题】：下载文件的大小受限制，下载文件过大会导致内存溢出
【原因】：文件获取后响应输出的过程，文件数据是存储在 `byte` 数组中的

**Comment by rj-hwang** [comment]
参考以下两个方法去尝试实现 zero-copy 下载文件：

1. [ServerResponse.BodyBuilder#body(BodyInserter)](https://github.com/spring-projects/spring-framework/blob/v5.0.3.RELEASE/spring-webflux/src/main/java/org/springframework/web/reactive/function/server/ServerResponse.java#L413)
2. [BodyInserters.fromResource(Resource)](https://github.com/spring-projects/spring-framework/blob/v5.0.3.RELEASE/spring-webflux/src/main/java/org/springframework/web/reactive/function/BodyInserters.java#L134)

`.body(BodyInserters.fromResource(FileSystemResource("$fileRootDir/${it.path}")))`

**Comment by laujeff23** [comment]
参考了上面的代码，解决了下载文件太大内存溢出的问题，代码已提交到 `master` 分支，详见 [commit-2a54899](https://github.com/simter/simter-file/commit/2a5489918d86335ab1df40b886c0d78dc95b24d6)

**Comment by rj-hwang** [comment]
`GET /{id}` should response `404 Not Found` if not exists.
Fixed on [83c4cd6](https://github.com/simter/simter-file/commit/83c4cd6c8fceb275229cbaf542b1c51ade9107c9).
