### ISSUE TITLE
上传文件的 mongo 持久化实现

### ISSUE THREAD

**Issue by rj-hwang** [simter/simter-file#2]

**Comment by BallsperCat** [comment]
创建分支号：feature/upload-persistence，开始执行任务。

**Comment by BallsperCat** [comment]
@BallsperCat

**Comment by BallsperCat** [comment]
【接口设计】@smart-jie @rj-hwang  附件持久层保存接口设计如下：
`/**  `
`   * 保存附件信息`
`   *`
`   * @param entity 要保存的附件`
`   */`
`fun save(entity: Attachment): Unit`

**Comment by rj-hwang** [comment]
由于现时的 jdbc 驱动都不是响应式的，postgres 暂时还没有相应的官方响应式 jdbc 驱动（[这里](https://stackoverflow.com/questions/42299455/spring-webflux-and-reading-from-database)有些第三方的资料说明，还有 [alaisi/postgres-async-driver](https://github.com/alaisi/postgres-async-driver))，现时支持响应式的数据库只有 MongoDB、Apache Cassandra 和 Redis，初步定下使用 MongoDB，按这个方向先进行下去。spring.io 上的这篇 blog 《[Going reactive with Spring Data](https://spring.io/blog/2016/11/28/going-reactive-with-spring-data)》介绍了基本的使用。

如下的链接是一些使用非响应式驱动数据库的一些变通做法，纯做阅读对比：

- [Spring 5 WebFlux and JDBC: To Block or Not to Block](https://dzone.com/articles/spring-5-webflux-and-jdbc-to-block-or-not-to-block) - 这里的做法我觉得最佳
- [聊聊 Spring Boot 2.0 的 WebFlux](https://www.bysocket.com/?p=1987)

**Comment by BallsperCat** [comment]
收到。

**Comment by rj-hwang** [comment]
SpringData + MongoDB + Reactive 的参考例子：
- [官方范例](https://github.com/spring-projects/spring-data-examples/tree/master/mongodb/reactive)、[中文解析](http://dev.dafan.info/detail/203631?p=28-68-39)
- [A quick look into Reactive Streams with Spring Data and MongoDB](https://lankydanblog.com/2017/07/16/a-quick-look-into-reactive-streams-with-spring-data-and-mongodb/)

**Comment by rj-hwang** [comment]
直接使用 ReactiveCrudRepository 的话，接口就变为这样了：

```
fun save(entity: Attachment): Mono<Attachment>
```

**Comment by rj-hwang** [comment]
审阅了 [commit-b4ba6f7](https://github.com/simter/simter-file/commit/b4ba6f75a9f55463bde6487705e1b400d3914392) 的代码，需要作如下重大变动：

1.  gftaxi-lease-data 模块应该只包含基础的东西，如 DAO、Service、PO、DTO 的定义，不能包含任何 mongo 的具体实现的配置和实现代码
2. 新增 simter-file-data-reactive-mongo 子模块，将依赖 mongo 的一切都放在这个模块内
3. gftaxi-lease-dependencies 作相应的依赖管理修改
4. gftaxi-lease-starter 模块增加对 simter-file-data-reactive-mongo 的依赖，使系统默认使用 mono 实现（通过 profiles 来配置）

**Comment by BallsperCat** [comment]
【提交说明】本次提交完成 spring-data-jpa 依赖和附件 Service 和 Dao 接口设计，请查阅：[代码对比](https://github.com/simter/simter-file/compare/5ea563...73b9d6)

**Comment by rj-hwang** [comment]
两点错误：
1. 不应该添加 spring-data-jpa 依赖，因为 ReactiveCrudRepository 不是 JPA！！！应该添加 spring-data-commons 依赖。
2. Service 接口不是响应式的

**Comment by BallsperCat** [comment]
【提交说明】修正上述审核问题并重新提交，请查阅：[代码对比](https://github.com/simter/simter-file/compare/f4c4bd...b58eec)

**Comment by rj-hwang** [comment]
需再补充 Service 的默认实现类

**Comment by BallsperCat** [comment]
【提交说明】本次提交新增了附件 Service 实现类和整理接口注释和提交日志，详见：[代码对比](https://github.com/simter/simter-file/commit/6d4dd5f7cba98d7e12f676e47fb4c26078f223ab)

**Comment by rj-hwang** [comment]
核查 OK，可以合并到主干。

**Comment by BallsperCat** [comment]
已合并到 master 主分支，详见：https://github.com/simter/simter-file/commit/af1b6a6ba560cf5b87ec05c6922f1976cfbfe8a7

**Comment by BallsperCat** [comment]
`AttachmentServiceImpl` 补充 `@Component` 注解，详见 [commit-65d3d58](https://github.com/simter/simter-file/commit/65d3d5824f1a09a0ac3443f12bc32e2699b4ea9d)

**Comment by BallsperCat** [comment]
【任务汇报】在做 AttachmentDao 单元测试时因配置原因无法生成“embeddedMongoServer”实体类，导致单元测试出错，未能找出配置出错的地方。单元测试的配置和代码已提交，详见：[代码明细](https://github.com/simter/simter-file/compare/d0374a...99f006)

**Comment by rj-hwang** [comment]
核查代码有如下问题：

1. `EmbeddedMongoAutoConfiguration` 只能在单元测试中使用，直接配置在主要的 `ApplicationConfiguration` 类上是不合理的，生产环境不可能使用 EmbeddedMongo。
2. `EnableReactiveMongoRepositories`  需要添加 `AttachmentDao` 的扫描，否则不会自动生成该接口的实现
3. maven 配置只需依赖 `spring-boot-starter-data-mongodb-reactive` 即可，其它对项目无用的包不应依赖进来
4. 单元测试一般使用针对 mongo 环境的 [@DataMongoTest](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-testing-autoconfigured-mongo-test)，当然使用 `@SpringBootTest` 也可以，只是过于笨重。
5. `Attachment`  po 添加 `@org.springframework.data.mongodb.core.mapping.Document` 注解。
6. 单元测试不通过估计是 EmbeddedMongo 下载失败导致，自己手动到 https://www.mongodb.org/dl/win32/x86_64 下载相应的 mongo 版本放到用户目录下的 `.embedmongo` 子目录下解决了。我将项目的 EmbeddedMongo 由默认的 3.2.2 升级到了 3.5.5，可以到 `IP222 的 /bak/mongo/embedmongo.rar` 下载覆盖到本地即可。

由于你的提交日志为临时信息，我没有采用，项目经重整后已合并回 master 分支（开发分支改名为  feature/mongo-persistence），详见 [commit-456283b](https://github.com/simter/simter-file/commit/456283be1ee5f449f9958f38978583a6dbd747c2)。
