### ISSUE TITLE
文件视图 Http 接口实现

### ISSUE THREAD

**Issue by laujeff23** [simter/simter-file#25]

**Comment by laujeff23** [comment]
实现文件视图 Http 接口，已合并到 `master` 分支，详见：[commit-a08fa27](https://github.com/simter/simter-file/commit/a08fa276a3af9e10b2d80830e631b1e3cc03f7cf)

**Comment by laujeff23** [comment]
更改文件视图请求 uri 为 GET /attachment，已提交到 `master`，详见：[commit-4e6f9d9](https://github.com/simter/simter-file/commit/4e6f9d991ab68c450c4b2a55f696fc6062bb7a88)

**Comment by rj-hwang** [comment]
FileViewXXX 需要更名为 AttachmentViewXXX

**Comment by laujeff23** [comment]
相应更名为 AttachmentViewXXX，详见 [commit-24fb0d2](https://github.com/simter/simter-file/commit/24fb0d2d4cac84eac2299eee0081821536e2bf4b)。

**Comment by rj-hwang** [comment]
`GET /attachment/{id}` should response `404 Not Found` if not exists.
Fixed on [26779a2](https://github.com/simter/simter-file/commit/26779a2208ab1b3706fe6fd4252fa13440f76b2c).
