### ISSUE TITLE
实现上传文件的 Http 接口

### ISSUE THREAD

**Issue by rj-hwang** [simter/simter-file#3]
See [Http Interfaces / Upload One File](https://github.com/simter/simter-file/wiki/Upload-One-File)

**Comment by rj-hwang** [comment]
@Smart-Jie @BallsperCat 保存到服务器的物理文件规则为：

1. 通过属性 `app.file.root` 配置根路径，默认配置为 `/data/files`。
2. 第一级子路经为当前年月，格式为 `yyyyMM`，如 `201801`。
3. 文件名格式为 `yyyyMMddTHHmmss-{id}.{ext}`，如 `20180101T1230-4f89741c-8d7f-46a4-bf3c-97139f7523c7.jpg`。

例：/data/files/201801/20180101T123045-4f89741c-8d7f-46a4-bf3c-97139f7523c7.jpg

**Comment by BallsperCat** [comment]
@rj-hwang 已收到。

**Comment by rj-hwang** [comment]
此提交 [commit-fbad403](https://github.com/simter/simter-file/commit/fbad40354f23e89a735ce825730b824c1c3c82cd) 不符合最基本的项目要求，附件保存路径也不符合上述的要求。

**Comment by laujeff23** [comment]
按项目要求修正代码，已提交 [commit-3f84101](https://github.com/simter/simter-file/commit/3f841014f7abf02543028397a446ceca4346dd4d)，单元测试未完成。

**Comment by rj-hwang** [comment]
代码存在如下问题：

1. 请求路径不符合 [Upload-One-File](https://github.com/simter/simter-file/wiki/Upload-One-File) 的接口设计要求。
2. UploadFileHandler.saveFileToLocal 方法不是响应式的，因为保存文件是 IO 操作，会导致线程堵塞，其返回值应该设计为 响应式的 Mono，并以响应式的方式执行保存文件的 IO 操作。
3. UploadFileHandler.saveFileToLocal 内需缓存 `fileNameWithExt.lastIndexOf(".")` 的值，而不是重复调用。
4. 文件保存的子目录格式不符合要求，是 `yyyyMM` 不是 `yyyy-MM`。
5. 在编写实现类时要高度重视单元测试，要测试先行。
6. 类注释的标题必须以句号结尾。
7. git 提交日志的首个字母要大写。

**Comment by laujeff23** [comment]
修改 [Upload-One-File](https://github.com/simter/simter-file/wiki/Upload-One-File) 接口文档的 Response 为无 Content-Type

**Comment by laujeff23** [comment]
修改 [Upload-One-File](https://github.com/simter/simter-file/wiki/Upload-One-File) 接口文档 Request 的 Content-Type 为 multipart/form-data

**Comment by laujeff23** [comment]
【提交说明】

1. 按接口设计要求修正请求路径
2. 添加一个变量缓存 `fileNameWithExt.lastIndexOf(".")` 的值
3. 修正文件保存的子目录为 `yyyyMM`
4. 添加单元测试
5. pom 文件添加 `nio-multipart-parser` 依赖以修复单元测试报的 `No multipart HttpMessageReader` 异常

其中未能完成以响应式的方式执行 IO 操作，代码详见：[commit-d69d60a](https://github.com/simter/simter-file/commit/d69d60ab8adc50383ded41d2f3217b483bb429c4)

**Comment by rj-hwang** [comment]
复审存在的问题：
1. UploadFileHandlerTest 放错包，tech.simter.file.rest.webflux.sample.UploadFileHandlerTest 应改为正规的 tech.simter.file.rest.webflux.handler.UploadFileHandlerTest
2. UploadFileHandlerTest 缺类注释信息和 `@author`，不要抄过来就算，要改成实际的
3. 不要则单元测试中使用 assert 关键字来断言，因为其默认的异常信息无法显示详细的原因
4. Location 的实现不符合接口设计要求，应为 /{id} 不是 {id}
5. UploadFileHandlerTest 验证文件保存是否成功的代码不佳
6. 无法验证 UploadFileHandler 是否生成了正确的 Attachment 实例

除第 6 点外，1-5 问题已在 [commit-5218a52](https://github.com/simter/simter-file/commit/5218a526c8039ff0fa991d8c77f5c27cc2395ea3) 修正。

**Comment by rj-hwang** [comment]
找到一些 WebFlux 上传文件的例子，留作参考：
1. Spring 源码中的一个上传文件的单元测试例子：[MultipartIntegrationTests.java](https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/test/java/org/springframework/web/reactive/function/MultipartIntegrationTests.java)
2. [stackoverflow 上关于添加 nio-multipart-parser 依赖的帖子](https://stackoverflow.com/questions/45981256/file-upload-with-functional-webflux#answer-45995477)

**Comment by rj-hwang** [comment]
重构了 UploadFileHandler 及其单元测试的代码，简化代码逻辑为：
1. 构建 Attachment 实例
2. 保存上传的文件
3. 保存 Attachment 实例
4. 生成响应

注：利用 FilePart#transferTo 的返回值是 Mono 实例这个特征将整个过程以响应式的方式串联在一起处理。

代码详见 [commit-bc5d425](https://github.com/simter/simter-file/commit/bc5d4252b8f043646f4d5a31de6bae481261dc2f)，已合并回主干。

**Comment by laujeff23** [comment]
【发现的问题】：上传文件的长度超过 `int` 的最大值时，会出现 `integer overflow` 异常
【原因】
UploadFileHandler 中使用了 [bodyToFlux()](https://github.com/simter/simter-file/blob/e1d635d483c2c26ef6f3914de29059d0b8bfb45b/simter-file-rest-webflux/src/main/kotlin/tech/simter/file/rest/webflux/handler/UploadFileHandler.kt#L40)，`bodyToFlux()` 方法内部运行调用了 [SynchronossPartHttpMessageReader.accept()](https://github.com/spring-projects/spring-framework/blob/v5.0.3.RELEASE/spring-web/src/main/java/org/springframework/http/codec/multipart/SynchronossPartHttpMessageReader.java#L125) 方法，`accept()` 方法中使用了 `int` 来保存文件长度

**Comment by rj-hwang** [comment]
我更新了你回复内的超链接，改为连接到相应的 commit 而不是 master，因为随着时间的推进 master 的代码会变，从而导致超链接很有可能在未来的某个时间开始就失效了。

**Comment by rj-hwang** [comment]
查阅了一下资料，发现可以使用如下新的知识点去处理上传文件的保存：

1. [`FilePart#content()`](https://github.com/spring-projects/spring-framework/blob/v5.0.3.RELEASE/spring-web/src/main/java/org/springframework/http/codec/multipart/Part.java#L53) 方法返回 `Flux<DataBuffer>` 类型。
2. [`DataBufferUtils#write(Publisher<DataBuffer>, AsynchronousFileChannel, long)`](https://github.com/spring-projects/spring-framework/blob/v5.0.3.RELEASE/spring-core/src/main/java/org/springframework/core/io/buffer/DataBufferUtils.java#L362) 工具方法则可异步保存 `DataBuffer` 数据到文件，其单元测试见[这里](https://github.com/spring-projects/spring-framework/blob/v5.0.3.RELEASE/spring-core/src/test/java/org/springframework/core/io/buffer/DataBufferUtilsTests.java#L200)。（注意 API 的说明，需要自行释放资源）

java 的 nio 就这样与 reactive 联系在一起了！

**Comment by rj-hwang** [comment]
在分支 [rj-try-DataBufferUtils.write](https://github.com/simter/simter-file/tree/rj-try-DataBufferUtils.write) 上作尝试，但单元测试失败，生成的文件为空，暂时找不到原因。

**Comment by rj-hwang** [comment]
Close by release [0.8.0](https://github.com/simter/simter-file/commits/0.8.0).
