### ISSUE TITLE
单个文件 Http 接口实现

### ISSUE THREAD

**Issue by laujeff23** [simter/simter-file#30]

**Comment by laujeff23** [comment]
实现单个文件 Http 接口，代码已合并到 `master` 分支，详见 [commit-bee7ab4](https://github.com/simter/simter-file/commit/bee7ab4d29b8c8de079ee5087fe341bca4f83729)

**Comment by rj-hwang** [comment]
FileFormXXX 需要更名为 AttachmentFormXXX。

**Comment by laujeff23** [comment]
相应更名为 AttachmentFormXXX，详见 [commit-88ef3ee](https://github.com/simter/simter-file/commit/88ef3ee892605299172dc2078284a4c9dd04858a)。
