### ISSUE TITLE
单个文件信息展现页面

### ISSUE THREAD

**Issue by laujeff23** [simter/simter-file#31]

**Comment by laujeff23** [comment]
[Add file form page](https://github.com/simter/simter-file-static/commit/ae3ebe3e5523b1f0c1c5d983e9b02893e7427e39)，代码已提交到 [simter-file-static](https://github.com/simter/simter-file-static) 的 `master` 分支

**Comment by rj-hwang** [comment]
'file form' need rename to 'attachment form'.

**Comment by laujeff23** [comment]
相应更名为 'attachment form'，详见 [commit-ee35f89](https://github.com/simter/simter-file-static/commit/ee35f89b5328cc3a7b3de1d61a07c057a58d07a5)。
